// Render curated content into the homepage, preserving its metadata head.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const { profile: p, papers } = JSON.parse(fs.readFileSync(path.join(root, 'content/site.json'), 'utf8'));
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const link = (label, url) => `<a href="${escape(url)}" target="_blank" rel="noreferrer">${escape(label)}</a>`;
function authors(paper) {
  const names = (paper.authors || []).map(a => typeof a === 'string' ? escape(a) : a.url ? link(a.name, a.url) : escape(a.name));
  const joined = names.length < 2 ? names.join('') : names.slice(0, -1).join(', ') + (names.length > 2 ? ', and ' : ' and ') + names.at(-1);
  return names.length || paper.date ? `(${names.length ? 'with ' + joined : ''}${paper.date ? (names.length ? ', ' : '') + escape(paper.date) : ''})` : '';
}
function renderPaper(paper, index) {
  const expandable = paper.category !== 'Work in Progress' || paper.abstract;
  const id = `paper-detail-${index}`;
  const status = paper.status ? (paper.links?.['Working Paper'] ? link(`[${paper.status}]`, paper.links['Working Paper']) : escape(paper.status)) : '';
  return `<article class="paper">
    <div class="paper-summary"><span class="paper-main">
      <span class="paper-title">${escape(paper.title)}</span>${expandable ? ` <button class="abstract-button" type="button" aria-expanded="true" aria-controls="${id}" hidden>[Click for abstract]</button>` : ''}
      <span class="paper-authors">${authors(paper)}</span>
      <span class="paper-venue">${status}</span>
    </span></div>
    ${expandable ? `<div class="paper-detail" id="${id}"><p class="paper-abstract">${escape(paper.abstract || 'Abstract forthcoming.')}</p><div class="paper-links">${Object.entries(paper.links || {}).filter(([label]) => label !== 'Working Paper').map(([label, url]) => link(`[${label}]`, url)).join(' ')}</div></div>` : ''}
  </article>`;
}
const groups = ['Published and Accepted Papers', 'Working Papers', 'Work in Progress'].map(category => {
  const items = papers.map((paper, index) => ({paper, index})).filter(({paper}) => paper.category === category);
  return items.length ? `<section class="paper-group"><h2>${category}</h2>${items.map(({paper, index}) => renderPaper(paper, index)).join('\n')}</section>` : '';
}).join('\n');
const contacts = [['Email', p.email], ['Office', p.office], ['Location', p.location]].filter(([, value]) => value).map(([label, value]) => {
  const [local, domain] = label === 'Email' ? value.split('@') : [];
  return `<dt>${label}</dt><dd>${label === 'Email' ? `<a href="mailto:${escape(value)}">${escape(local)}<br>[at] ${escape(domain)}</a>` : escape(value)}</dd>`;
}).join('\n');
const body = `<body>
  <!-- Generated by scripts/build_site.cjs from content/site.json. -->
  <main class="page" id="top">
    <aside class="sidebar">
      <div class="profile-intro">
      <h1>${escape(p.name)}</h1>
      ${p.photo ? `<img id="portrait" src="${escape(p.photo)}" alt="Portrait of ${escape(p.name)}">` : ''}
      <p class="profile-name">${escape(p.role)}</p>
      </div>
      <div class="profile-contact" id="contact">
      <p class="profile-role">${p.affiliationUrl ? link(p.affiliation, p.affiliationUrl) : escape(p.affiliation)}</p>
      <dl id="contact-list">${contacts}</dl>
      <div class="socials" id="social-links">${Object.entries(p.links || {}).map(([label, url]) => link(label, url)).join('\n')}</div>
      </div>
    </aside>
    <div class="content">
      <section id="about"><h2>Welcome!</h2>
        <p class="intro">${p.bioHtml || escape(p.bio)}</p>
        <p class="tagline">${escape(p.tagline)}</p>
      </section>
      <hr>
      <section class="cv-section"><h2><a id="cv-link" href="${escape(p.cv)}">Curriculum Vitae</a></h2></section>
      <hr>
      <section class="research" id="research"><div class="papers" id="paper-list">${groups}</div></section>
    </div>
  </main>
  <footer><p>&copy; <span id="year">${new Date().getFullYear()}</span> ${escape(p.name)}</p></footer>
  <script src="app.js" defer></script>
</body>`;
const file = path.join(root, 'index.html');
const html = fs.readFileSync(file, 'utf8');
if (!/<body>[\s\S]*<\/body>/.test(html)) throw new Error('Homepage body not found');
fs.writeFileSync(file, html.replace(/<body>[\s\S]*<\/body>/, () => body.replace(/[ \t]+$/gm, '')));
console.log(`Rendered profile and ${papers.length} papers into index.html`);
